import { IAccount } from "./IAccount";
import { ICompany } from "./ICompany";
import { IUser } from "./IUser";

export interface IDevice {
  _id: string;
  address: string;
  numberOfApartment: string;
  number: string;
  type: string;
  manufacturer: string;
  model: string;
  location: string;
  isSeal: boolean;
  installationDate: Date | null;
  dateOfSealing: Date | null;
  commissioningDate: Date | null;
  periodOfCheck: string;
  checkDate?: Date | null;
  assignment: string;
  firstData?: number;
  firstDataDay?: number;
  firstDataNight?: number;
  firstDataT1?: number;
  firstDataT2?: number;
  firstDataT3?: number;
  lastData?: number;
  lastDataDay?: number;
  lastDataNight?: number;
  lastDataT1?: number;
  lastDataT2?: number;
  lastDataT3?: number;
  difference?: number;
  differenceDay?: number;
  differenceNight?: number;
  differenceT1?: number;
  differenceT2?: number;
  differenceT3?: number;
  docs: string[];
  tariff: string;
  account: IAccount;
  company: ICompany;

  checkMessage?: string;
}
export type DeviceData = {
  address: string;
  numberOfApartment: string;
  number: string;
  type: string;
  manufacturer: string;
  model: string;
  location: string;
  isSeal: boolean;
  installationDate: Date | null;
  dateOfSealing: Date | null;
  commissioningDate: Date | null;
  periodOfCheck: string;
  checkDate?: Date | null;
  assignment: string;
  firstData?: number | string;
  firstDataDay?: number | string;
  firstDataNight?: number | string;
  firstDataT1?: number | string;
  firstDataT2?: number | string;
  firstDataT3?: number | string;
  docs: string[];
  tariff: string;
  account: string;
  company: string;
};
